# Generated by Django 5.1.1 on 2024-09-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_productspecification_producttype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                error_messages={
                    "name": {
                        "max_length": "The price must be between 0 and 99999999.99"
                    }
                },
                help_text="Miximum 99999999.99",
                max_digits=10,
                verbose_name="Discount price",
            ),
            preserve_default=False,
        ),
    ]
